SUPABASE_URL = "https://kunzcmsbrljxdeyeeqgi.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bnpjbXNicmxqeGRleWVlcWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjQ0NzgsImV4cCI6MjA3ODkwMDQ3OH0.d12uEEyndup2ABz674seiuhHQgXR98ESUXupfogx1J4"
